### ISSUE TITLE
pocket-Volume output changes significantly while using single frame vs Multiple frames

### ISSUE THREAD

**Issue by elvismartis** [POVME/POVME#36]
I have been experiencing a strange observation. Initially, I use aligned PDB trajectory file (2000 frames) to compute pocket-volumes defined by  ligand. Further, if I extract one of these frames from the aligned PDB trajectory and compute pocket-volume using identical settings, the volumes differ significantly compared to the same frame while a part of the trajectory. For example, 6000 A^3 (part of trajectory) vs 280 A^3 (as single PBD).
Can anyone help me understand this behaviour?

**Comment by YHli2019** [comment]
Hi Elvismartis,
    Have you checked the volume trajectory in pymol?

**Comment by elvismartis** [comment]
Thanks @YHli2019.
It seems that when single frame is used, POVME detects only the volume of the ligand and not of the pocket. Any reason for this behaviour?

**Comment by YHli2019** [comment]
That's not reasonable. Any possibilities that the structure of the single frame is different compared with the others? According to what POVME says, the script defines at least 3 A around the atoms of the ligand. So what do you mean by POVME doesn't detect the pocket? Any figures?

**Comment by elvismartis** [comment]
This issue was seen when I tried to use "definebyLigand", however, if I strip the ligand from the trajectory and define the pocket using inclusion sphere, then I get correct volumes.
Thanks @YHli2019
