### ISSUE TITLE
Error in analysis workflow example 

### ISSUE THREAD

**Issue by computational-chemist** [POVME/POVME#44]
Command : 

cd analysis_workflow_example/
source runWorkflow.sh
...

While the calculation was in progress, the following error occurred :

-bash: /home/u06/miniconda2/bin/binding_site_overlap.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory
-bash: /home/u06/miniconda2/bin/cluster.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "../analyzeClusterMembershipInGroups.py", line 4, in <module>
    data = [i.split() for i in open('cluster_members.csv').readlines()]
IOError: [Errno 2] No such file or directory: 'cluster_members.csv'
-bash: /home/u06/miniconda2/bin/pocketPointsPca.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory

Can you tell me what the solution is?

**Comment by j-wags** [comment]
Same as #45, you'll need to change the hardcoded paths in the scripts.
