### ISSUE TITLE
Question about error in 'Clustering and PCA example'

### ISSUE THREAD

**Issue by computational-chemist** [POVME/POVME#45]
The calculation for the previous two examples went well.

I was just following 'Clustering and PCA example' in README.md.

Command :

cd analysis_workflow_example/
source runWorkflow.sh
...

While other calculation of volume of binding site was in progress, the following error occurred :

-bash: /home/u06/miniconda2/bin/binding_site_overlap.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory
-bash: /home/u06/miniconda2/bin/cluster.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory
Traceback (most recent call last):
File "../analyzeClusterMembershipInGroups.py", line 4, in
data = [i.split() for i in open('cluster_members.csv').readlines()]
IOError: [Errno 2] No such file or directory: 'cluster_members.csv'
-bash: /home/u06/miniconda2/bin/pocketPointsPca.py: /gpfs/amarolab/j5wagner/POVME/2017_08_17_POVME_circle_test_fixing/miniconda2/bin/python: bad interpreter: No such file or directory

Can you tell me what the solution is?

**Comment by j-wags** [comment]
Unfortunately the developer (me 5 years ago) didn't know how to use relative paths in their code. You'll need to search through the scripts and update the paths to be appropriate for your file system
