### ISSUE TITLE
povme installation error

### ISSUE THREAD

**Issue by DDGmichigan** [POVME/POVME#47]
Hi can POVME work with python3.7?
I am not able to get it installed. please do provide some details as I am not a Python coder and finding it hard to install and run on my ensemble structures generated from accelerated MD.
Thanks

**Comment by j-wags** [comment]
This was answered in #33 

For python3 compatibility, consider using [POVME2.2.X,](https://git.durrantlab.pitt.edu/jdurrant/POVME/blob/2.2.2/README.md) which is still being developed at the Durrant lab.
